---
######################################
# Setup docker APT or YUM repository
######################################
- include: setup-apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - docker-install-all
    - docker-install-setup
